USE award_log;
ALTER TABLE sys_permission ADD COLUMN parent_id INT(11) DEFAULT NULL COMMENT '父权限ID';
ALTER TABLE sys_permission ADD COLUMN description VARCHAR(255) DEFAULT NULL COMMENT '权限描述';
ALTER TABLE sys_permission ADD COLUMN update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';